/**
 * Build-time script: reads OpenAPI YAML/JSON from ./specs/ and writes one .ts file per spec
 * under ./generated/ (e.g. get_job_postings.yaml → generated/get_job_postings.ts),
 * plus an index.ts that exports a single openApiToolRegistrar combining all.
 */
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { parse as parseYaml } from "yaml";

const __dirname = dirname(fileURLToPath(import.meta.url));
const SPECS_DIR = join(__dirname, "specs");
const OUT_DIR = join(__dirname, "generated");

type OpenAPISpec = {
  paths?: Record<
    string,
    {
      get?: OpenAPIOperation;
      post?: OpenAPIOperation;
      put?: OpenAPIOperation;
      delete?: OpenAPIOperation;
      patch?: OpenAPIOperation;
    }
  >;
};

type OpenAPIOperation = {
  operationId?: string;
  summary?: string;
  description?: string;
  parameters?: Array<{
    name: string;
    in: string;
    required?: boolean;
    schema?: { type?: string; default?: unknown };
  }>;
  requestBody?: {
    content?: {
      "application/json"?: { schema?: Record<string, unknown> };
    };
  };
};

const HTTP_METHODS = ["get", "post", "put", "delete", "patch"] as const;

function loadSpec(path: string): unknown {
  const content = readFileSync(path, "utf-8");
  const ext = path.slice(path.lastIndexOf("."));
  if (ext === ".json") {
    return JSON.parse(content) as unknown;
  }
  if (ext === ".yaml" || ext === ".yml") {
    return parseYaml(content) as unknown;
  }
  throw new Error(`Unsupported spec extension: ${ext}`);
}

function toToolName(
  operationId: string | undefined,
  path: string,
  method: string
): string {
  if (operationId) {
    return (
      operationId.replace(/\W+/g, "_").replace(/^_|_$/g, "") || "operation"
    );
  }
  const pathPart = path.replace(/\//g, "_").replace(/^_|_$/g, "") || "path";
  return `${method}_${pathPart}`;
}

function buildZodSchemaExpr(operation: OpenAPIOperation): string {
  const parts: string[] = [];
  for (const p of operation.parameters ?? []) {
    const type = p.schema?.type ?? "string";
    const optional = !p.required;
    let expr =
      type === "integer" || type === "number" ? "z.number()" : "z.string()";
    if (optional) expr += ".optional()";
    if (p.schema?.default !== undefined)
      expr += `.default(${JSON.stringify(p.schema.default)})`;
    parts.push(`${p.name}: ${expr}`);
  }
  if (operation.requestBody?.content?.["application/json"]?.schema) {
    parts.push("body: z.unknown().optional()");
  }
  if (parts.length === 0) return "z.object({})";
  return `z.object({ ${parts.join(", ")} }).strict()`;
}

function escapeStr(s: string): string {
  return JSON.stringify(s);
}

function specNameFromPath(specPath: string): string {
  return (
    specPath
      .replace(/\.(yaml|yml|json)$/i, "")
      .split(/[/\\]/)
      .pop() ?? "spec"
  );
}

function collectOperations(
  spec: OpenAPISpec,
  specName: string
): Array<{
  toolName: string;
  path: string;
  method: string;
  operation: OpenAPIOperation;
}> {
  const out: Array<{
    toolName: string;
    path: string;
    method: string;
    operation: OpenAPIOperation;
  }> = [];
  const paths = spec.paths ?? {};
  const seen = new Set<string>();

  for (const [path, pathItem] of Object.entries(paths)) {
    if (!pathItem || typeof pathItem !== "object") continue;
    for (const method of HTTP_METHODS) {
      const op = (pathItem as Record<string, OpenAPIOperation | undefined>)[
        method
      ];
      if (!op) continue;
      const baseName = toToolName(op.operationId, path, method);
      const toolName = seen.has(baseName)
        ? `${specName}_${baseName}`
        : baseName;
      seen.add(baseName);
      out.push({ toolName, path, method, operation: op });
    }
  }
  return out;
}

function generateTsForSpec(
  ops: Array<{
    toolName: string;
    path: string;
    method: string;
    operation: OpenAPIOperation;
    specName: string;
  }>
): string {
  const lines: string[] = [
    "// AUTO-GENERATED by openapi/generate-openapi-tools.ts — do not edit by hand",
    "",
    'import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";',
    'import type { Services, ToolRegistrar } from "@workday-mcp/mcp-core";',
    'import { isRecord } from "@workday-mcp/mcp-core";',
    'import { z } from "zod";',
    'import { executeOpenApiRequest } from "../execute.js";',
    "",
    "export const openApiToolRegistrar: ToolRegistrar = (server: McpServer, services: Services) => {",
  ];

  for (const { toolName, path, method, operation } of ops) {
    const title = operation.summary ?? toolName;
    const description =
      operation.description ??
      operation.summary ??
      `${method.toUpperCase()} ${path}`;
    const zodSchemaExpr = buildZodSchemaExpr(operation);

    lines.push(`  server.registerTool(`);
    lines.push(`    ${escapeStr(toolName)},`);
    lines.push(
      `    { title: ${escapeStr(title)}, description: ${escapeStr(description)}, inputSchema: ${zodSchemaExpr} },`
    );
    lines.push(`    async (input: unknown) => {`);
    lines.push(`      const baseUrl = services.config.workday?.baseUrl ?? "";`);
    lines.push(`      if (!baseUrl) {`);
    lines.push(
      `        return { content: [{ type: "text", text: JSON.stringify({ error: "workday.baseUrl not configured" }) }], isError: true };`
    );
    lines.push(`      }`);
    lines.push(
      `      const params = (isRecord(input) ? input : {}) as Record<string, unknown>;`
    );
    lines.push(`      const pathParams: Record<string, string> = {};`);
    lines.push(`      const query: Record<string, string> = {};`);
    lines.push(`      let body: unknown;`);
    for (const p of operation.parameters ?? []) {
      const safeName = /^[a-zA-Z_][a-zA-Z0-9_]*$/.test(p.name)
        ? p.name
        : JSON.stringify(p.name);
      if (p.in === "path") {
        lines.push(
          `      if (typeof params.${safeName} === "string") pathParams[${escapeStr(p.name)}] = params.${safeName};`
        );
      } else if (p.in === "query") {
        lines.push(
          `      if (params.${safeName} !== undefined) query[${escapeStr(p.name)}] = String(params.${safeName});`
        );
      }
    }
    if (operation.requestBody?.content?.["application/json"]) {
      lines.push(`      if (params.body !== undefined) body = params.body;`);
    }
    lines.push(
      `      return executeOpenApiRequest(services, { baseUrl, method: ${escapeStr(method.toUpperCase())}, path: ${escapeStr(path)}, pathParams, query, body });`
    );
    lines.push(`    }`);
    lines.push(`  );`);
    lines.push("");
  }

  lines.push("};");
  return lines.join("\n");
}

function toRegistrarIdentifier(specBaseName: string): string {
  return specBaseName.replace(/-/g, "_").replace(/\W/g, "_") + "Registrar";
}

function main(): void {
  let specFiles: string[] = [];
  try {
    specFiles = readdirSync(SPECS_DIR)
      .filter((f) => /\.(yaml|yml|json)$/i.test(f))
      .map((f) => join(SPECS_DIR, f))
      .sort();
  } catch {
    specFiles = [];
  }

  mkdirSync(OUT_DIR, { recursive: true });

  const specBaseNames: string[] = [];
  let totalTools = 0;

  for (const specPath of specFiles) {
    const raw = loadSpec(specPath) as OpenAPISpec;
    const specName = specNameFromPath(specPath);
    const ops = collectOperations(raw, specName);
    const opsWithSpec = ops.map((o) => ({ ...o, specName }));
    const outFileName = specName + ".ts";
    const outPath = join(OUT_DIR, outFileName);
    const content =
      opsWithSpec.length > 0
        ? generateTsForSpec(opsWithSpec)
        : [
            "// AUTO-GENERATED by openapi/generate-openapi-tools.ts — no operations in spec",
            "",
            'import type { ToolRegistrar } from "@workday-mcp/mcp-core";',
            "",
            "export const openApiToolRegistrar: ToolRegistrar = () => {};",
            "",
          ].join("\n");
    writeFileSync(outPath, content, "utf-8");
    specBaseNames.push(specName);
    totalTools += opsWithSpec.length;
    console.log(`Wrote ${outPath} (${opsWithSpec.length} tools)`);
  }

  const indexLines: string[] = [
    "// AUTO-GENERATED by openapi/generate-openapi-tools.ts — do not edit by hand",
    "",
    'import type { ToolRegistrar } from "@workday-mcp/mcp-core";',
    "",
  ];
  if (specBaseNames.length > 0) {
    for (const base of specBaseNames) {
      const ident = toRegistrarIdentifier(base);
      indexLines.push(
        `import { openApiToolRegistrar as ${ident} } from "./${base}.js";`
      );
    }
    indexLines.push("");
    indexLines.push(
      "export const openApiToolRegistrar: ToolRegistrar = (server, services) => {"
    );
    for (const base of specBaseNames) {
      indexLines.push(`  ${toRegistrarIdentifier(base)}(server, services);`);
    }
    indexLines.push("};");
  } else {
    indexLines.push(
      "export const openApiToolRegistrar: ToolRegistrar = () => {};"
    );
  }
  const indexPath = join(OUT_DIR, "index.ts");
  writeFileSync(indexPath, indexLines.join("\n"), "utf-8");
  console.log(
    `Wrote ${indexPath} (combined ${specBaseNames.length} spec(s), ${totalTools} tools total)`
  );
}

main();
